"""Generates a ready-to-use polyfills.js file for the user's project."""

from pathlib import Path
from typing import List
from datetime import datetime

from .polyfill_service import PolyfillRecommendation


def generate_polyfills_file(
    recommendations: List[PolyfillRecommendation],
    output_path: str
) -> str:
    """Write a polyfills.js file with all necessary imports. Returns the output path."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "/**",
        " * Polyfills for browser compatibility",
        f" * Auto-generated by Cross Guard on {timestamp}",
        " *",
        " * Import this file at the TOP of your entry point:",
        " *",
        " *   import './polyfills';",
        " *",
        " * Make sure to install dependencies first:",
        " *   npm install <packages listed below>",
        " */",
        "",
    ]

    npm_packages = []
    for rec in recommendations:
        if rec.polyfill_type == 'npm' and rec.packages:
            npm_packages.append(rec.packages[0].npm_package)

    if npm_packages:
        lines.append("// Required packages:")
        lines.append(f"// npm install {' '.join(sorted(npm_packages))}")
        lines.append("")

    for rec in recommendations:
        if rec.polyfill_type == 'npm' and rec.packages:
            lines.append(f"// {rec.feature_name}")
            lines.append(rec.packages[0].import_statement)
            lines.append("")

    if not any(rec.polyfill_type == 'npm' for rec in recommendations):
        lines.append("// No npm polyfills needed.")
        lines.append("// See CSS fallbacks in Cross Guard report for other recommendations.")
        lines.append("")

    content = "\n".join(lines)

    output = Path(output_path)
    output.write_text(content, encoding='utf-8')

    return str(output)


def generate_polyfills_content(
    recommendations: List[PolyfillRecommendation]
) -> str:
    """Same as generate_polyfills_file but returns the content string instead of writing."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "/**",
        " * Polyfills for browser compatibility",
        f" * Auto-generated by Cross Guard on {timestamp}",
        " *",
        " * Import this file at the TOP of your entry point:",
        " *",
        " *   import './polyfills';",
        " */",
        "",
    ]

    for rec in recommendations:
        if rec.polyfill_type == 'npm' and rec.packages:
            lines.append(f"// {rec.feature_name}")
            lines.append(rec.packages[0].import_statement)
            lines.append("")

    return "\n".join(lines)
