"""Whitebox tests for polyfill internals -- singleton, reload, load/save, generator."""

import json
import re
import pytest
from pathlib import Path
from unittest.mock import patch

from src.polyfill.polyfill_loader import (
    PolyfillLoader,
    get_polyfill_loader,
    load_polyfill_map,
    save_polyfill_map,
    POLYFILL_MAP_PATH,
)
from src.polyfill.polyfill_service import PolyfillService
from src.polyfill.polyfill_generator import generate_polyfills_content


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def loader():
    return get_polyfill_loader()


@pytest.fixture
def service():
    return PolyfillService()


@pytest.fixture
def npm_recs(service):
    return service.get_recommendations({'fetch', 'promises'}, set(), {'ie': '11'})


# ---------------------------------------------------------------------------
# Singleton pattern
# ---------------------------------------------------------------------------

class TestSingleton:
    @pytest.mark.whitebox
    def test_factory_returns_same_instance(self):
        assert get_polyfill_loader() is get_polyfill_loader()


# ---------------------------------------------------------------------------
# Reload
# ---------------------------------------------------------------------------

class TestReload:
    @pytest.mark.whitebox
    def test_reload_preserves_data(self, loader):
        loader.reload()
        assert loader.get_polyfill('fetch') is not None


# ---------------------------------------------------------------------------
# load_polyfill_map / save_polyfill_map
# ---------------------------------------------------------------------------

class TestLoadSave:
    @pytest.mark.whitebox
    def test_load_returns_all_sections(self):
        data = load_polyfill_map()
        assert isinstance(data, dict)
        for key in ('javascript', 'css', 'html', 'metadata'):
            assert key in data

    @pytest.mark.whitebox
    def test_save_creates_valid_json(self, tmp_path):
        out = tmp_path / 'polyfill_map.json'
        test_data = {
            'metadata': {'version': '1.0.0'},
            'javascript': {'test': {'name': 'Test', 'polyfillable': True, 'packages': []}},
            'css': {}, 'html': {},
        }
        with patch('src.polyfill.polyfill_loader.POLYFILL_MAP_PATH', out):
            assert save_polyfill_map(test_data) is True
        loaded = json.loads(out.read_text(encoding='utf-8'))
        assert loaded['javascript']['test']['name'] == 'Test'


# ---------------------------------------------------------------------------
# Content generation internals
# ---------------------------------------------------------------------------

class TestGenerateContent:
    @pytest.mark.whitebox
    def test_header_imports_and_timestamp(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        assert 'Auto-generated by Cross Guard' in content
        assert "import 'whatwg-fetch';" in content
        assert re.search(r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', content)

