"""Tests for polyfill file/content generation."""

import pytest
from pathlib import Path

from src.polyfill.polyfill_service import (
    PolyfillService,
    PolyfillRecommendation,
    PolyfillPackage,
)
from src.polyfill.polyfill_generator import (
    generate_polyfills_file,
    generate_polyfills_content,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def service():
    return PolyfillService()


@pytest.fixture
def npm_recs(service):
    """Recommendations with npm packages only."""
    return service.get_recommendations(
        unsupported_features={'fetch', 'promises'},
        partial_features=set(),
        browsers={'ie': '11'},
    )


@pytest.fixture
def fallback_recs(service):
    """Recommendations with CSS fallback only."""
    return service.get_recommendations(
        unsupported_features={'css-grid'},
        partial_features=set(),
        browsers={'ie': '11'},
    )


@pytest.fixture
def mixed_recs(service):
    """Both npm and fallback recommendations."""
    return service.get_recommendations(
        unsupported_features={'fetch', 'css-grid', 'dialog'},
        partial_features=set(),
        browsers={'ie': '11'},
    )


@pytest.fixture
def empty_recs():
    return []


# ---------------------------------------------------------------------------
# generate_polyfills_content
# ---------------------------------------------------------------------------

class TestGenerateContent:
    def test_header_present(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        assert '/**' in content
        assert 'Auto-generated by Cross Guard' in content
        assert "import './polyfills';" in content

    def test_npm_imports_present(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        assert "import 'whatwg-fetch';" in content

    def test_feature_name_as_comment(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        assert '// Fetch API' in content
        assert '// JavaScript Promises' in content

    def test_fallback_not_in_content(self, fallback_recs):
        """Fallback-only recs produce no imports — just a 'No npm polyfills needed' note."""
        content = generate_polyfills_content(fallback_recs)
        assert 'import' not in content or "import './polyfills'" in content

    def test_empty_recs_still_valid(self, empty_recs):
        content = generate_polyfills_content(empty_recs)
        assert 'Auto-generated by Cross Guard' in content

    def test_content_is_string(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        assert isinstance(content, str)

    def test_content_has_timestamp(self, npm_recs):
        content = generate_polyfills_content(npm_recs)
        # Timestamp format: YYYY-MM-DD HH:MM:SS
        import re
        assert re.search(r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', content)


# ---------------------------------------------------------------------------
# generate_polyfills_file
# ---------------------------------------------------------------------------

class TestGenerateFile:
    def test_creates_file(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        result = generate_polyfills_file(npm_recs, str(out))
        assert Path(result).exists()

    def test_returns_path_string(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        result = generate_polyfills_file(npm_recs, str(out))
        assert result == str(out)

    def test_file_contains_imports(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(npm_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert "import 'whatwg-fetch';" in content

    def test_file_has_install_command(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(npm_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert 'npm install' in content

    def test_file_has_install_packages(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(npm_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert 'whatwg-fetch' in content

    def test_file_encoding_utf8(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(npm_recs, str(out))
        # Read as bytes and verify UTF-8
        raw = out.read_bytes()
        raw.decode('utf-8')  # should not raise

    def test_fallback_only_file(self, tmp_path, fallback_recs):
        """File should say 'No npm polyfills needed' when only CSS fallbacks."""
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(fallback_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert 'No npm polyfills needed' in content

    def test_mixed_file_has_imports_and_header(self, tmp_path, mixed_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(mixed_recs, str(out))
        content = out.read_text(encoding='utf-8')
        # Should contain npm imports but not fallback code
        assert "import 'whatwg-fetch';" in content or "dialog-polyfill" in content
        assert 'Auto-generated by Cross Guard' in content

    def test_empty_recs_file(self, tmp_path, empty_recs):
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(empty_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert 'No npm polyfills needed' in content

    def test_overwrite_existing_file(self, tmp_path, npm_recs):
        out = tmp_path / 'polyfills.js'
        out.write_text('OLD CONTENT', encoding='utf-8')
        generate_polyfills_file(npm_recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert 'OLD CONTENT' not in content
        assert 'Auto-generated' in content

    def test_nested_directory_path(self, tmp_path, npm_recs):
        out = tmp_path / 'deep' / 'nested' / 'polyfills.js'
        out.parent.mkdir(parents=True)
        result = generate_polyfills_file(npm_recs, str(out))
        assert Path(result).exists()


# ---------------------------------------------------------------------------
# Specific package content verification
# ---------------------------------------------------------------------------

class TestSpecificPackageContent:
    """Verify that the generated content uses the correct import statements from polyfill_map."""

    @pytest.mark.parametrize("feature_id,expected_import", [
        ('fetch', "import 'whatwg-fetch';"),
        ('intersectionobserver', "import 'intersection-observer';"),
        ('requestidlecallback', "import 'requestidlecallback-polyfill';"),
        ('abortcontroller', "import 'abortcontroller-polyfill/dist/polyfill-patch-fetch';"),
        ('globalthis', "import 'core-js/features/global-this';"),
        ('classlist', "import 'classlist-polyfill';"),
    ])
    def test_import_statement_in_generated_content(self, service, feature_id, expected_import):
        recs = service.get_recommendations(
            unsupported_features={feature_id},
            partial_features=set(),
            browsers={'ie': '11'},
        )
        content = generate_polyfills_content(recs)
        assert expected_import in content, (
            f"Expected '{expected_import}' in generated content for {feature_id}"
        )

    @pytest.mark.parametrize("feature_id,expected_npm", [
        ('fetch', 'whatwg-fetch'),
        ('intersectionobserver', 'intersection-observer'),
        ('structuredclone', '@ungap/structured-clone'),
        ('broadcastchannel', 'broadcast-channel'),
        ('dialog', 'dialog-polyfill'),
    ])
    def test_npm_package_in_install_command(self, service, feature_id, expected_npm, tmp_path):
        recs = service.get_recommendations(
            unsupported_features={feature_id},
            partial_features=set(),
            browsers={'ie': '11'},
        )
        out = tmp_path / 'polyfills.js'
        generate_polyfills_file(recs, str(out))
        content = out.read_text(encoding='utf-8')
        assert expected_npm in content, (
            f"Expected '{expected_npm}' in file for {feature_id}"
        )


# ---------------------------------------------------------------------------
# Multi-line import statements
# ---------------------------------------------------------------------------

class TestMultiLineImports:
    """Some packages have multi-line import statements (e.g., resizeobserver, structuredclone)."""

    def test_multiline_import_preserved(self, service):
        recs = service.get_recommendations(
            unsupported_features={'structuredclone'},
            partial_features=set(),
            browsers={'ie': '11'},
        )
        assert len(recs) == 1
        import_stmt = recs[0].packages[0].import_statement
        # structuredClone import has 2 lines
        assert '\n' in import_stmt or 'structuredClone' in import_stmt
