"""HTML element/attribute/input-type to Can I Use feature ID mappings."""

# Elements
HTML_ELEMENTS = {
    'dialog': 'dialog',
    'details': 'details',
    'summary': 'details',
    'template': 'template',
    'picture': 'picture',
    # 'source' not mapped here -- it's used in video/audio too
    'track': 'webvtt',
    'video': 'video',
    'audio': 'audio',
    'canvas': 'canvas',
    'svg': 'svg',
    'meter': 'meter',
    'progress': 'progress',
    'datalist': 'datalist',
    'output': 'output-element',
    'time': 'html5semantic',
    'mark': 'html5semantic',
    'main': 'html5semantic',
    'section': 'html5semantic',
    'article': 'html5semantic',
    'aside': 'html5semantic',
    'header': 'html5semantic',
    'footer': 'html5semantic',
    'nav': 'html5semantic',
    'figure': 'html5semantic',
    'figcaption': 'html5semantic',
    'slot': 'shadowdomv1',
    'wbr': 'wbr-element',
    'ruby': 'ruby',
    'rt': 'ruby',
    'rp': 'ruby',
    'rb': 'ruby',
    'rtc': 'ruby',
    'menu': 'menu',
    'portal': 'portals',
}

# Input types
HTML_INPUT_TYPES = {
    'date': 'input-datetime',
    'datetime-local': 'input-datetime',
    'time': 'input-datetime',
    'month': 'input-datetime',
    'week': 'input-datetime',
    'color': 'input-color',
    'range': 'input-range',
    'search': 'input-search',
    'tel': 'input-email-tel-url',
    'url': 'input-email-tel-url',
    'email': 'input-email-tel-url',
    'number': 'input-number',
    'file': 'input-file-accept',
}

# Global attributes
HTML_ATTRIBUTES = {
    'datetime': 'html5semantic',
    'allow': 'permissions-policy',
    'srcset': 'srcset',
    'sizes': 'srcset',
    'nomodule': 'es6-module',
    'loading': 'loading-lazy-attr',
    'autocomplete': 'input-autocomplete-onoff',
    'autofocus': 'autofocus',
    'placeholder': 'input-placeholder',
    'required': 'form-validation',
    'pattern': 'input-pattern',
    'min': 'form-validation',
    'max': 'form-validation',
    'step': 'form-validation',
    'minlength': 'input-minlength',
    'maxlength': 'maxlength',
    'multiple': 'input-file-multiple',
    'accept': 'input-file-accept',
    'capture': 'html-media-capture',
    'contenteditable': 'contenteditable',
    'draggable': 'dragndrop',
    'ondragover': 'dragndrop',
    'ondrop': 'dragndrop',
    'ondragstart': 'dragndrop',
    'ondragend': 'dragndrop',
    'ondragenter': 'dragndrop',
    'ondragleave': 'dragndrop',
    'ondrag': 'dragndrop',
    'spellcheck': 'spellcheck-attribute',
    'translate': 'internationalization',
    'hidden': 'hidden',
    'download': 'download',
    'sandbox': 'iframe-sandbox',
    'srcdoc': 'iframe-srcdoc',
    'reversed': 'ol-reversed',
    'novalidate': 'form-validation',
    'formnovalidate': 'form-validation',
    'inputmode': 'input-inputmode',
    'readonly': 'readonly-attr',
    'tabindex': 'tabindex-attr',
    'ping': 'ping',
    'async': 'script-async',
    'defer': 'script-defer',
    'integrity': 'subresource-integrity',
    'is': 'custom-elementsv1',
    'formaction': 'form-submit-attributes',
    'formmethod': 'form-submit-attributes',
    'formenctype': 'form-submit-attributes',
    'formtarget': 'form-submit-attributes',
    'form': 'form-attribute',
    'shadowroot': 'declarative-shadow-dom',
    'shadowrootmode': 'declarative-shadow-dom',
    'oninput': 'input-event',
    'popover': 'popover',
    'popovertarget': 'popover',
    'popovertargetaction': 'popover',
    'inert': 'inert',
    'decoding': 'img-decoding-attribute',
    'fetchpriority': 'fetch-priority',
    'enterkeyhint': 'input-enterkeyhint',
    'blocking': 'blocking-render',
    'ontouchstart': 'touch',
    'ontouchmove': 'touch',
    'ontouchend': 'touch',
    'ontouchcancel': 'touch',
    'onpointerdown': 'pointer',
    'onpointermove': 'pointer',
    'onpointerup': 'pointer',
    'onpointercancel': 'pointer',
    'onpointerenter': 'pointer',
    'onpointerleave': 'pointer',
    'onpointerover': 'pointer',
    'onpointerout': 'pointer',
    'ongotpointercapture': 'pointer',
    'onlostpointercapture': 'pointer',
    'onfocusin': 'focusin-focusout-events',
    'onfocusout': 'focusin-focusout-events',
    'onhashchange': 'hashchange',
    'manifest': 'offline-apps',
    'onpageshow': 'page-transition-events',
    'onpagehide': 'page-transition-events',
    'onbeforeprint': 'beforeafterprint',
    'onafterprint': 'beforeafterprint',
    'scoped': 'style-scoped',
    'webkitdirectory': 'input-file-directory',
    'directory': 'input-file-directory',
}

# Attributes that only trigger features on specific elements
# (prevents false positives like "label" on <option> matching webvtt)
ELEMENT_SPECIFIC_ATTRIBUTES = {
    "track": {
        "label": "webvtt",
        "kind": "webvtt",
        "default": "webvtt",
        "srclang": "webvtt",
    },
    "details": {
        "open": "details",
    },
    "meter": {
        "high": "meter",
        "low": "meter",
        "optimum": "meter",
    },
    "link": {
        "as": "link-rel-preload",
    },
}

# Attribute value combinations
HTML_ATTRIBUTE_VALUES = {
    ('rel', 'preload'): 'link-rel-preload',
    ('rel', 'prefetch'): 'link-rel-prefetch',
    ('rel', 'dns-prefetch'): 'link-rel-dns-prefetch',
    ('rel', 'preconnect'): 'link-rel-preconnect',
    ('rel', 'modulepreload'): 'link-rel-modulepreload',
    ('rel', 'prerender'): 'link-rel-prerender',
    ('rel', 'icon'): 'link-icon-png',
    ('rel', 'noopener'): 'rel-noopener',
    ('rel', 'noreferrer'): 'rel-noreferrer',
    ('type', 'module'): 'es6-module',
    ('crossorigin', 'anonymous'): 'cors',
    ('crossorigin', 'use-credentials'): 'cors',
    ('referrerpolicy', 'no-referrer'): 'referrer-policy',
    ('referrerpolicy', 'origin'): 'referrer-policy',
    ('referrerpolicy', 'no-referrer-when-downgrade'): 'referrer-policy',
    ('referrerpolicy', 'origin-when-cross-origin'): 'referrer-policy',
    ('referrerpolicy', 'same-origin'): 'referrer-policy',
    ('referrerpolicy', 'strict-origin'): 'referrer-policy',
    ('referrerpolicy', 'strict-origin-when-cross-origin'): 'referrer-policy',
    ('referrerpolicy', 'unsafe-url'): 'referrer-policy',
    ('loading', 'lazy'): 'loading-lazy-attr',
    ('loading', 'eager'): 'loading-lazy-attr',
    ('type', 'image/svg+xml'): 'link-icon-svg',
    ('rel', 'import'): 'imports',
}

# Forms
HTML_FORM_FEATURES = {
    'form': 'forms',
    'fieldset': 'forms',
    'legend': 'forms',
    'label': 'forms',
    'input': 'forms',
    'textarea': 'forms',
    'select': 'forms',
    'option': 'forms',
    'button': 'forms',
}

# Media
HTML_MEDIA_FEATURES = {
    'video': 'video',
    'audio': 'audio',
    'source': 'video',
    'track': 'webvtt',
}

# Additional features detected by special logic
HTML_ADDITIONAL_FEATURES = {
    'srcset': 'srcset',
    'sizes': 'srcset',
    'dataset': 'dataset',
    'ruby': 'ruby',
    'menu': 'menu',
    'menuitem': 'menu',
    'meta-theme-color': 'meta-theme-color',
    'indeterminate-checkbox': 'indeterminate-checkbox',
    'input-file-directory': 'input-file-directory',
    'web-app-manifest': 'web-app-manifest',
    'svg-html5': 'svg-html5',
    'iframe-seamless': 'iframe-seamless',
    'selectlist': 'selectlist',
    'canvas-text': 'canvas-text',
    'passwordrules': 'passwordrules',
    'rel-noopener': 'rel-noopener',
    'svg-img': 'svg-img',
    'svg-fragment': 'svg-fragment',
    'media-fragments': 'media-fragments',
    'audiotracks': 'audiotracks',
    'videotracks': 'videotracks',
    'custom-elements': 'custom-elementsv1',
    'fieldset-disabled': 'fieldset-disabled',
    'portals': 'portals',
    'touch': 'touch',
    'pointer': 'pointer',
    'focusin-focusout-events': 'focusin-focusout-events',
    'hashchange': 'hashchange',
    'offline-apps': 'offline-apps',
    'page-transition-events': 'page-transition-events',
    'beforeafterprint': 'beforeafterprint',
    'imports': 'imports',
    'style-scoped': 'style-scoped',
    'input-email-tel-url': 'input-email-tel-url',
    'popover': 'popover',
    'inert': 'inert',
    'img-decoding-attribute': 'img-decoding-attribute',
    'fetch-priority': 'fetch-priority',
    'input-enterkeyhint': 'input-enterkeyhint',
    'blocking-render': 'blocking-render',
    'wai-aria': 'wai-aria',
    'mathml': 'mathml',
    'webvtt': 'webvtt',
    'datauri': 'datauri',
    'xhtml': 'xhtml',
    'webm': 'webm',
    'webp': 'webp',
    'mp3': 'mp3',
    'ogg-vorbis': 'ogg-vorbis',
    'ogv': 'ogv',
    'mpeg4': 'mpeg4',
    'aac': 'aac',
    'wav': 'wav',
    'flac': 'flac',
    'opus': 'opus',
    'avif': 'avif',
    'heif': 'heif',
    'jpeg2000': 'jpeg2000',
    'jpegxl': 'jpegxl',
    'jpegxr': 'jpegxr',
    'apng': 'apng',
    'hevc': 'hevc',
    'av1': 'av1',
}

# Special elements
HTML_SPECIAL_ELEMENTS = {
    'math': 'mathml',
}

# ARIA attributes
HTML_ARIA_ATTRIBUTES = {
    'role': 'wai-aria',
    'aria-label': 'wai-aria',
    'aria-labelledby': 'wai-aria',
    'aria-describedby': 'wai-aria',
    'aria-hidden': 'wai-aria',
    'aria-live': 'wai-aria',
    'aria-atomic': 'wai-aria',
    'aria-busy': 'wai-aria',
    'aria-controls': 'wai-aria',
    'aria-current': 'wai-aria',
    'aria-disabled': 'wai-aria',
    'aria-expanded': 'wai-aria',
    'aria-haspopup': 'wai-aria',
    'aria-invalid': 'wai-aria',
    'aria-pressed': 'wai-aria',
    'aria-selected': 'wai-aria',
    'aria-checked': 'wai-aria',
    'aria-valuemin': 'wai-aria',
    'aria-valuemax': 'wai-aria',
    'aria-valuenow': 'wai-aria',
    'aria-valuetext': 'wai-aria',
    'aria-modal': 'wai-aria',
    'aria-orientation': 'wai-aria',
    'aria-autocomplete': 'wai-aria',
    'aria-multiline': 'wai-aria',
    'aria-multiselectable': 'wai-aria',
    'aria-readonly': 'wai-aria',
    'aria-required': 'wai-aria',
    'aria-sort': 'wai-aria',
    'aria-level': 'wai-aria',
    'aria-posinset': 'wai-aria',
    'aria-setsize': 'wai-aria',
    'aria-owns': 'wai-aria',
    'aria-flowto': 'wai-aria',
    'aria-activedescendant': 'wai-aria',
    'aria-errormessage': 'wai-aria',
    'aria-details': 'wai-aria',
    'aria-keyshortcuts': 'wai-aria',
    'aria-roledescription': 'wai-aria',
}

# Media type values (for format detection)
HTML_MEDIA_TYPE_VALUES = {
    ('type', 'video/webm'): 'webm',
    ('type', 'video/ogg'): 'ogv',
    ('type', 'video/mp4'): 'mpeg4',
    ('type', 'video/av1'): 'av1',
    ('type', 'audio/webm'): 'webm',
    ('type', 'audio/ogg'): 'ogg-vorbis',
    ('type', 'audio/mpeg'): 'mp3',
    ('type', 'audio/mp3'): 'mp3',
    ('type', 'audio/wav'): 'wav',
    ('type', 'audio/flac'): 'flac',
    ('type', 'audio/aac'): 'aac',
    ('type', 'audio/opus'): 'opus',
    ('type', 'image/webp'): 'webp',
    ('type', 'image/avif'): 'avif',
    ('type', 'image/heif'): 'heif',
    ('type', 'image/heic'): 'heif',
    ('type', 'image/jp2'): 'jpeg2000',
    ('type', 'image/jxl'): 'jpegxl',
    ('type', 'image/jxr'): 'jpegxr',
    ('type', 'image/apng'): 'apng',
    ('type', 'audio/ac3'): 'ac3-ec3',
    ('type', 'audio/eac3'): 'ac3-ec3',
    ('type', 'audio/ec3'): 'ac3-ec3',
}

# CSP meta tags
HTML_CSP_ATTRIBUTES = {
    ('http-equiv', 'content-security-policy'): 'contentsecuritypolicy2',
    ('http-equiv', 'x-content-security-policy'): 'contentsecuritypolicy',
}

# Combined lookup for quick feature existence checks
ALL_HTML_FEATURES = {
    **HTML_ELEMENTS,
    **HTML_INPUT_TYPES,
    **HTML_FORM_FEATURES,
    **HTML_MEDIA_FEATURES,
    **HTML_ADDITIONAL_FEATURES,
    **HTML_ATTRIBUTES,
    **{attr: fid for attrs in ELEMENT_SPECIFIC_ATTRIBUTES.values() for attr, fid in attrs.items()},
    **{v: v for k, v in HTML_ATTRIBUTE_VALUES.items()},
    **HTML_SPECIAL_ELEMENTS,
    **HTML_ARIA_ATTRIBUTES,
    **{v: v for k, v in HTML_MEDIA_TYPE_VALUES.items()},
    **{v: v for k, v in HTML_CSP_ATTRIBUTES.items()},
}
